sudo: false
language: python
python:
  - "3.7"
  - "3.8"
install:
  - git clone https://github.com/pyhandle/hpy.git
  - (cd hpy/hpy-api && python setup.py install)
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
