sudo: false
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install https://github.com/pyhandle/hpy/archive/master.zip#subdirectory=hpy-api
  - pip install six blist unittest2 pytz
  - python setup.py install
script: python tests/tests.py
